name: Main workflow

# event
on: push

jobs:
  run-shell-command:
  # machine
    runs-on: ubuntu-latest
    steps:
    # array of objects with name and run keys
      - name: echo a string
        run: echo "Hello world"
      - name: nultiline script
        # pipe (|) form multiple command
        run: |
          node -v
          npm -v