name: Main workflow

# event ex: pull_request or more specific:
# on:
#   pull_request:
#     types: [closed, assigned, opened, reopened]
on: push

jobs:
  run-shell-command:
    # operating sistem
    # default shell is bash
    runs-on: ubuntu-latest
    steps:
    # array of objects with name and run keys
      - name: echo a string
        run: echo "Hello world"
      - name: nultiline script
        # pipe (|) form multiple command
        run: |
          node -v
          npm -v
      # step on python shell (default shell is bash)
      - name: python Command
        run: |
          import platform
          print(platform.processor())
        shell: python

  run-window-commands:
    # default shell for windows is powershell
    runs-on: windows-latest
    # wait for end of run-shell-command
    needs: ['run-shell-command']
    steps: 
      - name: Directory PowerShell
        run: Get-Location
      - name: Directory Bash
        run: pwd
        shell: bash

      